[project]
name = "gpkan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "gpjax==0.9.4",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "numpyro>=0.19.0",
    "scienceplots>=2.2.0",
    "scikit-learn>=1.8.0",
]

[tool.uv.workspace]
members = [
    "gpkan",
]
