[project]
name = "gpkanmodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aadle", email = "aarlmdl@gmail.com" }
]
requires-python = ">=3.12.8"
dependencies = []

[project.scripts]
gpkanmodel = "gpkanmodel:main"

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"
